export interface DisplayGroup {
  display_name: string;
  slug: string;
  /** @format int64 */
  sort_order: number;
}

/** Meta contains info describing the entity (event, venue, performer, etc.) */
export interface Meta {
  /** display group slug */
  display_group?: string;
  /**
   * popularity-feedback score
   * @format double
   */
  popularity_score?: number;
  /** algolia query id */
  query_id?: string;
  /**
   * algolia absolute result position
   * @format int64
   */
  result_position?: number;
  /** @format double */
  score_boost?: number;
  /** algolia index used */
  search_index?: string;
  /**
   * search score for this document
   * @format double
   */
  search_score?: number;
  /**
   * absolute sort order
   * @format int64
   */
  sort_order?: number;
}

export interface FullEvent {
  event: Event;
  /** Meta contains info describing the entity (event, venue, performer, etc.) */
  meta?: Meta;
  performers: Performer[];
  venue: Venue;
}

export interface Location {
  /** @format double */
  lat: number;
  /** @format double */
  lon: number;
}

export interface Venue {
  city: string;
  id: string;
  image_url: string;
  location?: Location;
  /** Meta contains info describing the entity (event, venue, performer, etc.) */
  meta?: Meta;
  metro: string;
  name: string;
  show_currency: boolean;
  slug: string;
  state: string;
  timezone: string;
}

export interface Performer {
  abbrev: string;
  category: string;
  category_group: string;
  contrast_color: string;
  display_type: string;
  hero_image_url: string;
  id: string;
  medium_name: string;
  /** Meta contains info describing the entity (event, venue, performer, etc.) */
  meta?: Meta;
  name: string;
  primary_color: string;
  short_name: string;
  slug: string;
}

export interface SearchResponse {
  /**
   * SearchID is the unique ID of the search session. It is the same as the request's SearchID value, if one was
   * provided; if one was not provided, it is a value generated by the server.
   *
   * in: header
   */
  'X-Gt-Search-Id'?: string;
  /**
   * SearchSequence is the sequence number of the search. It is the same as the request's SearchSequence value, if
   * one was provide and could be parsed as an int. Otherwise, it is 0.
   *
   * in: header
   * @format int64
   */
  'X-Gt-Search-Seq'?: number;
  display_groups?: DisplayGroup[];
  events?: FullEvent[];
  performers?: Performer[];
  venues?: Venue[];
}
